### ISSUE TITLE
Documentation in wrong categories?

### ISSUE THREAD

**Issue by kisielk** [supercollider/sc3-plugins#103]
It seems for a lot of the extensions the documentation is not categorized according to the hierarchy set up by the base SC distribution.

For example, a lot of the base distribution generator UGens are in `UGens > Generators`, eg: `UGens > Generators > PhysicalModels`.

However a whole bunch of the extensions place their help files into `UGens > PhysicalModels`. This makes it harder to browse the help system when looking for UGens in a particular class, or other UGens similar to one the user already knows. I feel like they should be consolidated in to either location.

**Comment by kisielk** [comment]
I'm willing to send some PRs to improve this if there is some consensus as to how things should be moved about.

**Comment by snappizz** [comment]
In the case of generators and physical models, it doesn't make much sense to put one category under the other because neither kind of UGen implies the other. e.g. there are non-generator physical models like NTube and DFM1. The help file should be categorized as both `UGens>Generators` and `UGens>Physical Models`.

Feel free to recategorize things and ask questions about anything that's uncertain. Thanks for volunteering to do this work! :)

**Comment by kisielk** [comment]
Right, I hadn't even considered that, glad I asked first :) I will keep the advice in mind when I see something looking at out of place. In fact I didn't know files could go in to multiple categories...

Anyway, I will close this issue for now since it doesn't really pertain to anything very specific. I will open up PRs as appropriate.
