### ISSUE TITLE
Install process difficult to follow

### ISSUE THREAD

**Issue by yaxu** [supercollider/sc3-plugins#176]
I run quite a lot of workshops etc dependent on supercollider with sc3-plugins, and have observed people find the instructions for installing sc3-plugins difficult to follow. 

Some quick suggestions for improvements:

1. make it so "release downloads" isn't a separate section, i.e. put download instructions as part of 'binary install'. Then people will be less likely press the green button and  end up trying to install the source with the binary instructions.
2. explicitly telling people not to press the green button is probably a good idea, most people seem to make this mistake at the moment. Or perhaps moving the install instructions off github itself which comes with a lot of confusing information + ui.
3. explaining that the install folder probably won't already exist, and needs creating.
4. explaining what to do if the part of the path is a hidden folder - I think this is the case under macos which makes things very difficult!
5. telling people how to evaluate by putting their cursor on the line and hitting shift-enter or whatever
6. maybe not call the section 'binary install' but just 'install', for those who don't know what 'a binary' means
7. make the link text 'download latest version' or something rather than 'github release page'

Or perhaps sc3-plugins should be rolled into the main release. The package is small by today's standards and I get the impression that most if not all people install them.

**Comment by patrickdupuis** [comment]
@yaxu Thanks for the feedback! 

Unfortunately, it is not possible for sc3plugins to be included into SC core. The sc3plugins are meant to be a repository of community developed and maintained set of extensions to SC. It is the nature of the project itself to live outside of core, so that people can experiment, do whatever, and offer their work for others to use. Although most of us install the plugins, the fact remains that they come with no guarantee and must be used with caution. 

It's possible for some of the plugins to be merged into core. I don't remember this ever happening, but it's possible. If you have any suggestions, please open an issue. Keep in mind that the original creator may not want their work to be merged in.

**Comment by patrickdupuis** [comment]
Also, the core SC library is alive and growing. There are new UGens in the works :)
