### ISSUE TITLE
Redirecting people to the sc3-plugins page

### ISSUE THREAD

**Issue by yaxu** [supercollider/sc3-plugins#290]
I'm still regularly helping out people who have found their way to this page https://github.com/supercollider/sc3-plugins/

They click the tempting 'download' button there which is for the source, and this leads to a lot of confusion in trying to follow the instructions.

I wonder if it would be better if the README could be reduced to a simple message redirecting them to this beautiful page: https://supercollider.github.io/sc3-plugins/

**Comment by yaxu** [comment]
Also I think the instructions could make clear that you need to download a version of sc3-plugins to match the supercollider version you have installed.

**Comment by yaxu** [comment]
Also this page directs people to 3.10 but many will want the 3.11 release candidate http://supercollider.github.io/sc3-plugins/

**Comment by yaxu** [comment]
With sc3plugins being so popular and useful, I'd again like to request a combined download of supercollider with sc3plugins included.

**Comment by brianlheim** [comment]
thanks @yaxu !

i've changed the repo description to "Community plugins for SC3. Hey! Don't click the "download" button here, go to https://supercollider.github.io/sc3-plugins/ instead!" -- is that better? https://github.com/supercollider/sc3-plugins

regarding changes to the readme and website, is is probably quickest and easiest if you submit a PR yourself. i'm sure someone from the SC org would be happy to merge it. i think we are planning to update the website once the rc becomes a proper release, for which we are only waiting on our release manager when he has the time. but i had actually forgotten about this website -- @joshpar take note :). i also edited our release instructions to include this step.

> With sc3plugins being so popular and useful, I'd again like to request a combined download of supercollider with sc3plugins included.

i understand this would be useful for some, but it's simply not going to happen. this repo is of significantly lower quality and activity compared to the main repo, and maintainers have no desire to give this any more 'official' status than it already has. the best thing to do at this point in my opinion is put effort toward distributing plugins through Quarks or some similar means, so that all community plugins can benefit and not only the ones grandfathered in via this repo.

**Comment by yaxu** [comment]
I'd be happy to make those website tweaks @brianlheim, but apologies if I'm being a bit dim.. Where is the repo for the sc3-plugins page? 
I can't see it here https://github.com/supercollider/supercollider.github.io

**Comment by patrickdupuis** [comment]
The sc3-plugins website is part of the sc3-plugins repository. Looking at it now, I see that it's all mixed in with the rest of the repo's contents. If you are familiar with Github Pages, it shouldn't be too difficult to sort out. Sorry I can't be of much help.

**Comment by telephon** [comment]
> Where is the repo for the sc3-plugins page?

https://github.com/supercollider/sc3-plugins

**Comment by yaxu** [comment]
Thanks @telephon !

**Comment by shimpe** [comment]
Now the github io page is perhaps a bit confusing?

![confusing](https://user-images.githubusercontent.com/732258/83961560-b4ca3b80-a894-11ea-8f93-4bb1f22e5679.png)
