### ISSUE TITLE
OS-X 10.10 cmake install error: Could not find a package configuration file provided by "Qt5Core" 

### ISSUE THREAD

**Issue by erikparr** [supercollider/sc3-plugins#74]
installing on os-x according to the README instructions throws errors about not finding Qt5Core ... help appreciated thx
>> $ sudo cmake -DSC_PATH= /Users/erikparr/SuperCollider

CMake Warning at QtCollider/CMakeLists.txt:5 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  lang/CMakeLists.txt:174 (include)

CMake Warning at QtCollider/CMakeLists.txt:6 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

etc etc etc...

**Comment by bagong** [comment]
Something went horribly wrong. Somehow cmake believes you want to build SuperCollider rather than the plugins. Is there a space between = and /Path to sc? If yes, that's probably it.
You shouldn't do an "in place" build either, git will be stressed, and your source and build files will be mixed.
At the end of the cmake command you have to point to the sc3-plugins source. So if you build in a folder that is a sibling of sc3-plugins, do something like 
    cmake -DSC_PATH=/Users/erikparr/SuperCollider ../sc3-plugins
Hey, and don't use sudo with cmake... ;)
Best

**Comment by erikparr** [comment]
ok thanks, the space was indeed the problem. there goes my unix cred. I also realized that downloading the zipped version found here wont work as it is missing the cmake files. I cloned the sc3-plugins directory instead and tried cmake again and everything worked.
